-- 022_knowledge_base_seed.sql — Phase 7 (Lexi)
-- Seeds the knowledge_base with bilingual FAQ/glossary/policy entries used
-- by Lexi's search_knowledge_base tool. Idempotent: each INSERT is guarded
-- by WHERE NOT EXISTS on title_en. Content is also editable at runtime via
-- the Admin Database Console (/admin/database -> knowledge_base).

INSERT INTO public.knowledge_base (title_en, title_bm, content_en, content_bm, tags)
SELECT 'What is GeoAI Talent Agent?', 'Apakah GeoAI Talent Agent?', 'GeoAI Talent Agent is JPN Sarawak''s geospatial platform for mapping teacher expertise. It shows where Master Trainer skills are concentrated on an interactive map of Sarawak, recommends qualified and available trainers near a workshop venue with travel-cost estimates, and manages a human-approved invitation workflow. It runs in English or Bahasa Melayu, one language at a time.', 'GeoAI Talent Agent ialah platform geospatial JPN Sarawak untuk memetakan kepakaran guru. Ia menunjukkan tumpuan kemahiran Jurulatih Utama pada peta interaktif Sarawak, mencadangkan jurulatih yang layak dan tersedia berhampiran tempat bengkel dengan anggaran kos perjalanan, dan mengurus aliran kerja jemputan yang diluluskan manusia. Ia berfungsi dalam Bahasa Inggeris atau Bahasa Melayu, satu bahasa pada satu masa.', ARRAY['overview', 'about', 'platform', 'sistem']
WHERE NOT EXISTS (SELECT 1 FROM public.knowledge_base WHERE title_en = 'What is GeoAI Talent Agent?');

INSERT INTO public.knowledge_base (title_en, title_bm, content_en, content_bm, tags)
SELECT 'Mode A — Explore (trainer heatmap)', 'Mod A — Terokai (peta haba jurulatih)', 'Mode A shows a heatmap of where trainer expertise is concentrated across Sarawak. Filter by ICT skills or teaching subjects with the checkboxes on the left. Zooming in (or clicking a PPD district pin) switches to individual trainer pins; click a pin to see the trainer''s school, district, roles, skills, and subjects. On login the map starts at your own district (admins see the whole state); use "Zoom out" to return to the statewide view.', 'Mod A menunjukkan peta haba tumpuan kepakaran jurulatih di seluruh Sarawak. Tapis mengikut kemahiran TMK atau mata pelajaran dengan kotak semak di sebelah kiri. Zum masuk (atau klik pin daerah PPD) menukar kepada pin jurulatih individu; klik pin untuk melihat sekolah, daerah, peranan, kemahiran dan subjek jurulatih. Semasa log masuk, peta bermula di daerah anda sendiri (pentadbir melihat seluruh negeri); guna "Zum keluar" untuk kembali ke paparan seluruh negeri.', ARRAY['mode a', 'explore', 'heatmap', 'peta haba', 'terokai']
WHERE NOT EXISTS (SELECT 1 FROM public.knowledge_base WHERE title_en = 'Mode A — Explore (trainer heatmap)');

INSERT INTO public.knowledge_base (title_en, title_bm, content_en, content_bm, tags)
SELECT 'Mode B — Find Trainers (venue search and recommendations)', 'Mod B — Cari Jurulatih (carian tempat dan cadangan)', 'Mode B recommends trainers for a workshop. Set the venue one of three ways: type a place name (autocomplete), match a school in the registry, or drop a pin on the map. Set the training start and end dates, optionally a title, the number of trainers needed, and a skill filter, then press "Find Available Trainers". The system checks date availability, computes travel distance and cost for each candidate, and ranks them. Select trainers, review the invitation email, and send.', 'Mod B mencadangkan jurulatih untuk bengkel. Tetapkan tempat melalui tiga cara: taip nama tempat (autolengkap), padankan sekolah dalam daftar, atau letak pin pada peta. Tetapkan tarikh mula dan tamat latihan, tajuk (pilihan), bilangan jurulatih diperlukan, dan tapisan kemahiran, kemudian tekan "Cari Jurulatih Tersedia". Sistem menyemak ketersediaan tarikh, mengira jarak dan kos perjalanan bagi setiap calon, dan menyusunnya. Pilih jurulatih, semak emel jemputan, dan hantar.', ARRAY['mode b', 'find trainers', 'venue', 'recommendation', 'cari jurulatih', 'tempat']
WHERE NOT EXISTS (SELECT 1 FROM public.knowledge_base WHERE title_en = 'Mode B — Find Trainers (venue search and recommendations)');

INSERT INTO public.knowledge_base (title_en, title_bm, content_en, content_bm, tags)
SELECT 'How is travel cost calculated?', 'Bagaimana kos perjalanan dikira?', 'Land travel cost is a deterministic formula from the travel_rates table, never guessed: RM1.00/km for total distances 0-500 km and RM0.90/km above 500 km, applied to the round trip. If the venue is under 150 km away, the cost is multiplied by the number of training days (daily return trips); at 150 km or more it is one round trip only (the trainer stays on-site). Flight and boat fares have no per-km rate, so they are estimated (web search or AI), cached, clearly labelled as estimates, and an admin can override them. All figures are indicative — verify with your finance officer before committing expenditure.', 'Kos perjalanan darat ialah formula tetap daripada jadual travel_rates, bukan tekaan: RM1.00/km untuk jumlah jarak 0-500 km dan RM0.90/km melebihi 500 km, dikira untuk perjalanan pergi balik. Jika tempat kurang 150 km, kos didarab dengan bilangan hari latihan (perjalanan ulang-alik harian); pada 150 km atau lebih, kos ialah satu perjalanan pergi balik sahaja (jurulatih menginap). Tambang penerbangan dan bot tiada kadar per km, jadi ia dianggarkan (carian web atau AI), disimpan, dilabel jelas sebagai anggaran, dan pentadbir boleh mengatasinya. Semua angka adalah anggaran — sahkan dengan pegawai kewangan sebelum berbelanja.', ARRAY['travel cost', 'kos perjalanan', 'formula', 'rm', 'mileage', 'flight', 'boat']
WHERE NOT EXISTS (SELECT 1 FROM public.knowledge_base WHERE title_en = 'How is travel cost calculated?');

INSERT INTO public.knowledge_base (title_en, title_bm, content_en, content_bm, tags)
SELECT 'Invitation workflow and trainer responses', 'Aliran kerja jemputan dan respons jurulatih', 'After a Mode B search you select trainers and press "Finalize & Invite Selected". You review and edit one shared invitation email (personalised per trainer with merge fields) before anything is sent — nothing goes out without this human approval step. Each trainer receives secure, single-use Accept/Decline links that expire in 7 days. Responses update the workshop automatically and notify the coordinator in-app. A trainer who accepted is locked out of overlapping searches for those dates.', 'Selepas carian Mod B, anda memilih jurulatih dan menekan "Muktamat & Jemput Yang Dipilih". Anda menyemak dan menyunting satu emel jemputan yang dikongsi (diperibadikan bagi setiap jurulatih dengan medan gabungan) sebelum apa-apa dihantar — tiada apa yang keluar tanpa langkah kelulusan manusia ini. Setiap jurulatih menerima pautan Terima/Tolak selamat, sekali guna, yang luput dalam 7 hari. Respons mengemas kini bengkel secara automatik dan memberitahu penyelaras dalam aplikasi. Jurulatih yang menerima dikunci daripada carian bertindih untuk tarikh tersebut.', ARRAY['invitation', 'jemputan', 'email', 'accept', 'decline', 'workflow']
WHERE NOT EXISTS (SELECT 1 FROM public.knowledge_base WHERE title_en = 'Invitation workflow and trainer responses');

INSERT INTO public.knowledge_base (title_en, title_bm, content_en, content_bm, tags)
SELECT 'Workshop statuses explained', 'Penerangan status bengkel', 'A workshop''s status rolls up from its trainer invitations. Draft: created, nothing sent yet. Pending Invite: at least one invitation is awaiting a response. Confirmed: enough trainers accepted (meets "trainers needed"). Declined: shown per-trainer when someone declines. Cancelled: the whole workshop was cancelled — its history is kept but it cannot be reopened. Per-trainer statuses are Pending Invite, Confirmed, or Declined.', 'Status bengkel dirumuskan daripada jemputan jurulatihnya. Draf: dicipta, belum ada yang dihantar. Menunggu Jemputan: sekurang-kurangnya satu jemputan menunggu respons. Disahkan: cukup jurulatih menerima (memenuhi "jurulatih diperlukan"). Ditolak: dipaparkan bagi setiap jurulatih yang menolak. Dibatalkan: seluruh bengkel dibatalkan — sejarahnya disimpan tetapi tidak boleh dibuka semula. Status bagi setiap jurulatih ialah Menunggu Jemputan, Disahkan, atau Ditolak.', ARRAY['status', 'draft', 'pending', 'confirmed', 'declined', 'cancelled', 'draf', 'disahkan']
WHERE NOT EXISTS (SELECT 1 FROM public.knowledge_base WHERE title_en = 'Workshop statuses explained');

INSERT INTO public.knowledge_base (title_en, title_bm, content_en, content_bm, tags)
SELECT 'Why can''t I change workshop dates?', 'Mengapa saya tidak boleh menukar tarikh bengkel?', 'Workshop dates are locked once invitations have been sent, because trainers accepted those specific dates. You can still edit the title and venue at any time (unless cancelled). To reschedule, cancel the workshop and create a new one with fresh invitations. Only Draft workshops (nothing sent) can have their dates edited or be permanently deleted.', 'Tarikh bengkel dikunci selepas jemputan dihantar, kerana jurulatih menerima tarikh tersebut. Anda masih boleh menyunting tajuk dan tempat pada bila-bila masa (kecuali dibatalkan). Untuk menjadualkan semula, batalkan bengkel dan cipta yang baharu dengan jemputan baharu. Hanya bengkel Draf (tiada yang dihantar) boleh disunting tarikhnya atau dipadamkan secara kekal.', ARRAY['dates', 'tarikh', 'locked', 'reschedule', 'edit', 'delete']
WHERE NOT EXISTS (SELECT 1 FROM public.knowledge_base WHERE title_en = 'Why can''t I change workshop dates?');

INSERT INTO public.knowledge_base (title_en, title_bm, content_en, content_bm, tags)
SELECT 'The Workshop Calendar', 'Kalendar Bengkel', 'The Calendar page shows all scheduled workshops in a month grid, colour-coded by status (teal = Confirmed, amber = Pending Invite, grey = Draft). Drafts are hidden by default — use the "Show drafts" toggle. Click a workshop chip for details: venue, dates, per-trainer responses, and (if you created it or are an admin) Edit, Cancel, or Delete-draft actions. You can filter by trainer name. Every active user can see the calendar.', 'Halaman Kalendar menunjukkan semua bengkel berjadual dalam grid bulanan, berkod warna mengikut status (teal = Disahkan, kuning = Menunggu Jemputan, kelabu = Draf). Draf disembunyikan secara lalai — guna togol "Tunjuk draf". Klik cip bengkel untuk butiran: tempat, tarikh, respons setiap jurulatih, dan (jika anda penciptanya atau pentadbir) tindakan Sunting, Batal, atau Padam draf. Anda boleh menapis mengikut nama jurulatih. Semua pengguna aktif boleh melihat kalendar.', ARRAY['calendar', 'kalendar', 'schedule', 'jadual', 'month']
WHERE NOT EXISTS (SELECT 1 FROM public.knowledge_base WHERE title_en = 'The Workshop Calendar');

INSERT INTO public.knowledge_base (title_en, title_bm, content_en, content_bm, tags)
SELECT 'Roles and permissions', 'Peranan dan kebenaran', 'There are two roles. Standard users can view all trainers and schools statewide, search, create workshops, and send invitations for their own workshops; their assigned district only sets where their map starts. Administrators (JPN) can additionally manage any workshop, approve and manage user accounts, and edit reference data in the Database console. New registrations start as "pending" until an admin approves them. Sensitive actions are always audit-logged.', 'Terdapat dua peranan. Pengguna biasa boleh melihat semua jurulatih dan sekolah di seluruh negeri, membuat carian, mencipta bengkel, dan menghantar jemputan untuk bengkel mereka sendiri; daerah yang ditetapkan hanya menentukan permulaan paparan peta mereka. Pentadbir (JPN) tambahan pula boleh mengurus mana-mana bengkel, meluluskan dan mengurus akaun pengguna, serta menyunting data rujukan dalam konsol Pangkalan Data. Pendaftaran baharu bermula sebagai "menunggu" sehingga diluluskan pentadbir. Tindakan sensitif sentiasa direkodkan dalam log audit.', ARRAY['roles', 'peranan', 'admin', 'permissions', 'kebenaran', 'pentadbir']
WHERE NOT EXISTS (SELECT 1 FROM public.knowledge_base WHERE title_en = 'Roles and permissions');

INSERT INTO public.knowledge_base (title_en, title_bm, content_en, content_bm, tags)
SELECT 'Changing the language (English / Bahasa Melayu)', 'Menukar bahasa (Bahasa Inggeris / Bahasa Melayu)', 'Use the EN/BM toggle in the top bar to switch the whole app between English and Bahasa Melayu. The app shows one language at a time (never both side by side). Fixed content comes from stored translations; free text such as workshop titles can be translated on demand. Your choice is remembered for a year.', 'Guna togol EN/BM pada bar atas untuk menukar seluruh aplikasi antara Bahasa Inggeris dan Bahasa Melayu. Aplikasi memaparkan satu bahasa pada satu masa (tidak sekali kedua-duanya). Kandungan tetap datang daripada terjemahan tersimpan; teks bebas seperti tajuk bengkel boleh diterjemah atas permintaan. Pilihan anda diingati selama setahun.', ARRAY['language', 'bahasa', 'toggle', 'translate', 'terjemah', 'en', 'bm']
WHERE NOT EXISTS (SELECT 1 FROM public.knowledge_base WHERE title_en = 'Changing the language (English / Bahasa Melayu)');

INSERT INTO public.knowledge_base (title_en, title_bm, content_en, content_bm, tags)
SELECT 'What can Lexi do (and not do)?', 'Apakah yang Lexi boleh (dan tidak boleh) lakukan?', 'Lexi can find and count trainers by skill or district, fetch a trainer''s engagement and travel history, check schedule availability for specific dates, explain how this system works, open screens for you, and answer general questions (clearly labelled as general knowledge). All counts, costs, and dates come from the real database — Lexi never makes figures up. Lexi cannot send emails, edit data, approve users, or change settings: those always go through the normal screens with human approval.', 'Lexi boleh mencari dan mengira jurulatih mengikut kemahiran atau daerah, mendapatkan sejarah penglibatan dan perjalanan jurulatih, menyemak ketersediaan jadual untuk tarikh tertentu, menerangkan cara sistem ini berfungsi, membuka skrin untuk anda, dan menjawab soalan umum (dilabel jelas sebagai pengetahuan umum). Semua kiraan, kos dan tarikh datang daripada pangkalan data sebenar — Lexi tidak pernah mereka-reka angka. Lexi tidak boleh menghantar emel, menyunting data, meluluskan pengguna, atau menukar tetapan: semuanya melalui skrin biasa dengan kelulusan manusia.', ARRAY['lexi', 'assistant', 'pembantu', 'ai', 'help', 'bantuan']
WHERE NOT EXISTS (SELECT 1 FROM public.knowledge_base WHERE title_en = 'What can Lexi do (and not do)?');

INSERT INTO public.knowledge_base (title_en, title_bm, content_en, content_bm, tags)
SELECT 'Search radius', 'Jejari carian', 'Both modes share a centre-point + radius filter, adjustable from 10 to 500 km (default 50 km) with the slider at the bottom right of the map. In Mode A the centre is a district or dropped pin (clear it for statewide); in Mode B the centre is always the workshop venue. Trainers outside the radius are excluded from results.', 'Kedua-dua mod berkongsi penapis titik tengah + jejari, boleh laras dari 10 hingga 500 km (lalai 50 km) dengan pelungsur di bahagian kanan bawah peta. Dalam Mod A, titik tengah ialah daerah atau pin yang diletakkan (kosongkan untuk seluruh negeri); dalam Mod B, titik tengah sentiasa tempat bengkel. Jurulatih di luar jejari dikecualikan daripada keputusan.', ARRAY['radius', 'jejari', 'km', 'slider', 'distance', 'jarak']
WHERE NOT EXISTS (SELECT 1 FROM public.knowledge_base WHERE title_en = 'Search radius');
